/**
 * Projects
 */
export const ADD_PROJECT = "ADD_PROJECT"
export const REMOVE_PROJECT = "REMOVE_PROJECT"
export const SET_PROJECT_NAME = "SET_PROJECT_NAME"
export const SET_PROJECT_WIDTH = "SET_PROJECT_WIDTH"
export const SET_PROJECT_HEIGHT = "SET_PROJECT_HEIGHT"
export const SET_GRID_SHOW = "SET_GRID_SHOW"
export const SET_GRID_SNAP = "SET_GRID_SNAP"
export const SET_GRID_SIZE = "SET_GRID_SIZE"

/**
 * Paths
 */
export const ADD_PATH = "ADD_PATH"
export const REMOVE_PATHS = "REMOVE_PATHS"
export const SET_PATH_NAME = "SET_PATH_NAME"
export const DEACTIVATE_PATHS = "DEACTIVATE_PATHS"
export const SET_ACTIVE_PATHS = "SET_ACTIVE_PATHS"
export const SET_RELATIVE_PATH = "SET_RELATIVE_PATH"
export const SET_CLOSED_PATH = "SET_CLOSED_PATH"
export const SET_FILLED_PATH = "SET_FILLED_PATH"

/**
 * Points
 */
export const ADD_POINT = "ADD_POINT"
export const REMOVE_POINTS = "REMOVE_POINTS"
export const SET_POINT_CODE = "SET_POINT_CODE"
export const DEACTIVATE_POINTS = "DEACTIVATE_POINTS"
export const SET_ACTIVE_POINTS = "SET_ACTIVE_POINTS"
export const SET_POINT_X = "SET_POINT_X"
export const SET_POINT_Y = "SET_POINT_Y"
export const SET_POINTS_X = "SET_POINTS_X"
export const SET_POINTS_Y = "SET_POINTS_Y"
export const SET_POINT_PARAMETERS = "SET_POINT_PARAMETERS"
