export const POINT_MAIN = "POINT_MAIN"
export const POINT_ANCHOR_QUAD = "POINT_ANCHOR_QUAD"
export const POINT_ANCHOR_CUB_FIRST = "POINT_ANCHOR_CUB_FIRST"
export const POINT_ANCHOR_CUB_SEC = "POINT_ANCHOR_CUB_SEC"
